# ---- Build stage ----
FROM node:24-alpine3.21 AS builder

WORKDIR /usr/src/api

COPY package*.json ./
RUN npm install 

COPY . .

RUN npx prisma generate
RUN npm run build

# ---- Production stage ----
FROM node:24-alpine3.21 AS production

WORKDIR /usr/src/api

COPY package*.json ./
# RUN npm install --omit=dev

COPY --from=builder /usr/src/api/node_modules ./node_modules
COPY --from=builder /usr/src/api/dist ./dist
COPY --from=builder /usr/src/api/generated ./generated
COPY --from=builder /usr/src/api/prisma ./prisma
COPY --from=builder /usr/src/api/prisma.config.ts ./prisma.config.ts

COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x entrypoint.sh

RUN mkdir -p uploads/profiles

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]
