# ---- Build stage ----
FROM node:24-alpine3.21 AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# ---- Production stage ----
FROM node:24-alpine3.21 AS production

WORKDIR /usr/src/app

COPY package*.json ./
# RUN npm install --omit=dev

COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/.next ./.next
COPY --from=builder /usr/src/app/public ./public
COPY --from=builder /usr/src/app/next.config.ts ./

EXPOSE 3000

CMD ["npm", "run", "start"]
